services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 54321:5432
    volumes:
      - ./db/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  mytheresa:
    build: .
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
    volumes:
      - ./config/conf.yaml:/etc/mytheresa/conf.yaml
    entrypoint: /mytheresa
    command: -config=/etc/mytheresa/conf.yaml
    ports:
      - 8082:8082
